INSERT INTO [dbo].[Equipment] ([Name], [Available], [NotInUse], [Destroyed], [Description], [RoomId])
VALUES
    ('Kamera przemysłowa', 1, 0, 0, 'Zaawansowane urządzenie do rejestrowania obrazu w środowisku przemysłowym.', 47),
    ('Skaner kodów kreskowych', 1, 0, 0, 'Urządzenie do odczytu kodów kreskowych z produktów.', 48),
    ('Drone', 1, 0, 0, 'Bezzałogowy statek powietrzny zdalnie sterowany.', 49),
    ('Laserowy wskaźnik', 1, 0, 0, 'Przenośne urządzenie emitujące wiązkę światła laserowego.', 50),
    ('Mikser kuchenny', 1, 0, 0, 'Elektryczne urządzenie do mieszania i ubijania składników kuchennych.', 51),
    ('Termometr', 1, 0, 0, 'Przyrząd służący do pomiaru temperatury.', 52),
    ('Głośniki Bluetooth', 1, 0, 0, 'Przenośne głośniki bezprzewodowe łączące się przez Bluetooth.', 53),
    ('Konsola do gier', 1, 0, 0, 'Urządzenie do rozrywki elektronicznej z możliwością grania w gry wideo.', 54),
    ('Powerbank', 1, 0, 0, 'Przenośne źródło zasilania do ładowania urządzeń elektronicznych.', 55),
    ('Tablet', 1, 0, 0, 'Przenośne urządzenie z ekranem dotykowym do pracy i rozrywki.', 56),
    ('Drukarka', 1, 0, 0, 'Urządzenie służące do drukowania dokumentów i obrazów na papierze.', 57),
    ('Słuchawki bezprzewodowe', 1, 0, 0, 'Bezprzewodowe słuchawki do słuchania muzyki i prowadzenia rozmów.', 58),
    ('Mysz komputerowa', 1, 0, 0, 'Urządzenie do sterowania kursora na ekranie komputera.', 59),
    ('Klawiatura', 1, 0, 0, 'Urządzenie do wprowadzania danych i sterowania komputerem.', 60),
    ('Monitor komputerowy', 1, 0, 0, 'Wyświetlacz do wyświetlania obrazu z komputera.', 61),
    ('Kamera internetowa', 1, 0, 0, 'Urządzenie do wideokonferencji i przesyłania obrazu przez internet.', 62),
    ('Waga łazienkowa', 1, 0, 0, 'Przyrząd do pomiaru masy ciała.', 63),
    ('Projektor multimedialny', 1, 0, 0, 'Urządzenie służące do wyświetlania obrazu i dźwięku na dużej powierzchni.', 64),
    ('Suszarka do włosów', 1, 0, 0, 'Elektryczne urządzenie do suszenia i stylizacji włosów.', 65),
    ('Ekspres do kawy', 1, 0, 0, 'Urządzenie do przygotowywania świeżo parzonej kawy.', 66),
    ('Smartfon', 1, 0, 0, 'Zaawansowany telefon komórkowy z funkcjami multimedialnymi i dostępem do internetu.', 67),
    ('Projektor do prezentacji', 1, 0, 0, 'Urządzenie służące do wyświetlania prezentacji na dużym ekranie.', 68),
    ('Gamingowy fotel', 1, 0, 0, 'Komfortowy fotel przeznaczony do długich sesji grania w gry komputerowe.', 69),
    ('Mikrofon studyjny', 1, 0, 0, 'Profesjonalny mikrofon do nagrywania dźwięku w studiach muzycznych.', 70),
    ('Projektor overhead', 1, 0, 0, 'Urządzenie do wyświetlania przezroczystych slajdów i dokumentów na dużym ekranie.', 71),
    ('Smart TV', 1, 0, 0, 'Telewizor z funkcjami internetowymi i możliwością dostępu do aplikacji.', 72),
    ('Czytnik e-booków', 1, 0, 0, 'Przenośne urządzenie do czytania książek elektronicznych.', 73),
    ('Głośnik komputerowy', 1, 0, 0, 'Urządzenie do odtwarzania dźwięku z komputera.', 74),
    ('Maszyna do szycia', 1, 0, 0, 'Elektryczna maszyna służąca do szycia tkanin.', 75),
    ('Suszarka do rąk', 1, 0, 0, 'Urządzenie do suszenia rąk po umyciu.', 76),
    ('Wideokamera', 1, 0, 0, 'Urządzenie do nagrywania wideo w wysokiej jakości.', 77),
    ('Monitor medyczny', 1, 0, 0, 'Ekran przeznaczony do wyświetlania obrazów medycznych.', 78),
    ('Prostownik', 1, 0, 0, 'Urządzenie do ładowania akumulatorów.', 79),
    ('Odkurzacz', 1, 0, 0, 'Elektryczne urządzenie do odkurzania powierzchni.', 80),
    ('Kalkulator naukowy', 1, 0, 0, 'Zaawansowany kalkulator do obliczeń naukowych i matematycznych.', 81),
    ('Monitor graficzny', 1, 0, 0, 'Wyświetlacz do edycji grafiki i projektowania.', 82),
    ('Kamera sportowa', 1, 0, 0, 'Kompaktowa kamera do nagrywania sportowych wydarzeń.', 83),
    ('Mikroskop', 1, 0, 0, 'Przyrząd optyczny do badania mikroskopowych struktur.', 84),
    ('Wzmacniacz audio', 1, 0, 0, 'Urządzenie wzmacniające dźwięk odtwarzany z różnych źródeł.', 85),
    ('Lodówka', 1, 0, 0, 'Urządzenie do przechowywania żywności w niskiej temperaturze.', 86),
    ('Kamera termowizyjna', 1, 0, 0, 'Urządzenie do obrazowania termicznego oparte na emisji promieniowania podczerwonego.', 87),
    ('Stacja pogodowa', 1, 0, 0, 'Urządzenie mierzące parametry pogodowe, takie jak temperatura, wilgotność i ciśnienie.', 88),
    ('Procesor', 1, 0, 0, 'Jednostka centralna komputera wykonująca operacje obliczeniowe.', 89),
    ('Router sieciowy', 1, 0, 0, 'Urządzenie do przekazywania danych między sieciami komputerowymi.', 90),
    ('Powerbank solarny', 1, 0, 0, 'Przenośne źródło zasilania z panelem słonecznym do ładowania urządzeń elektronicznych.', 91),
    ('Klawiatura mechaniczna', 1, 0, 0, 'Klawiatura komputerowa z mechanicznymi przełącznikami klawiszy.', 92),
     ('Klawiatura mechaniczna', 1, 0, 0, 'Klawiatura komputerowa z mechanicznymi przełącznikami klawiszy.', 92),
    ('Mikroskop elektronowy', 1, 0, 0, 'Zaawansowane urządzenie do badania mikrostruktur na poziomie atomowym.', 93),
    ('Przenośny projekt', 1, 0, 0, 'Kompaktowy projektor przeznaczony do prezentacji na różnych powierzchniach.', 94),
    ('Smartwatch dla dzieci', 1, 0, 0, 'Zegarek dla dzieci z funkcjami monitorowania i zabawowymi aplikacjami.', 95),
    ('Waga kuchenna', 1, 0, 0, 'Przyrząd do ważenia składników kuchennych podczas gotowania.', 96),
    ('Rower stacjonarny', 1, 0, 0, 'Urządzenie treningowe do jazdy rowerem w miejscu.', 97),
    ('Mikrofalówka', 1, 0, 0, 'Urządzenie do szybkiego podgrzewania i gotowania jedzenia.', 98),
    ('Wózek na zakupy', 1, 0, 0, 'Przenośny wózek z koszem do przewożenia zakupów.', 99),
    ('Pilot do telewizora', 1, 0, 0, 'Bezprzewodowe urządzenie służące do sterowania telewizorem.', 100),
    ('Kamera monitoringu', 1, 0, 0, 'Urządzenie do rejestrowania obrazu w celach monitoringu.', 101),
    ('Konsola do DJ-a', 1, 0, 0, 'Specjalizowana konsola do miksowania i odtwarzania muzyki dla DJ-ów.', 102),
    ('Kamera do mikroskopu', 1, 0, 0, 'Kamera umożliwiająca rejestrowanie obrazu z mikroskopu.', 103),
    ('Głośniki komputerowe', 1, 0, 0, 'Przenośne głośniki do podłączenia do komputera.', 104),
    ('Projektor holograficzny', 1, 0, 0, 'Urządzenie generujące trójwymiarowe obrazy holograficzne.', 105),
    ('Żelazko', 1, 0, 0, 'Urządzenie do wygładzania i prasowania tkanin.', 106),
     ('Smartgogle', 1, 0, 0, 'Zaawansowane okulary wirtualnej rzeczywistości z funkcjami rozszerzonej rzeczywistości.', 107),
    ('Konsola do gier przenośna', 1, 0, 0, 'Przenośna konsola do gier wideo.', 108),
    ('Mikrofon bezprzewodowy', 1, 0, 0, 'Bezprzewodowy mikrofon do nagrywania dźwięku.', 109),
    ('Laptop', 1, 0, 0, 'Przenośny komputer z klawiaturą, ekranem i baterią.', 110),
    ('Waga bagażowa', 1, 0, 0, 'Przyrząd do ważenia bagażu przed podróżą.', 111),
    ('Kamera termowizyjna', 1, 0, 0, 'Urządzenie do wykrywania i obrazowania promieniowania podczerwonego.', 112),
    ('Odtwarzacz MP3', 1, 0, 0, 'Przenośne urządzenie do odtwarzania plików dźwiękowych w formacie MP3.', 113),
    ('Smartwatch sportowy', 1, 0, 0, 'Zegarek z funkcjami monitorowania aktywności fizycznej i zdrowia.', 114),
    ('Monitor serwerowy', 1, 0, 0, 'Wyświetlacz przeznaczony do monitorowania pracy serwerów.', 115),
    ('Projektor kinowy', 1, 0, 0, 'Zaawansowany projektor do wyświetlania filmów na dużym ekranie.', 116),
    ('Kamera 360 stopni', 1, 0, 0, 'Urządzenie rejestrujące panoramiczne obrazy w pełnym kącie 360 stopni.', 117),
    ('Wiertarko-wkrętarka', 1, 0, 0, 'Elektryczne narzędzie służące do wiercenia i wkręcania śrub.', 118),
    ('Podgrzewacz do wody', 1, 0, 0, 'Urządzenie do podgrzewania wody w celach kuchennych lub użytkowych.', 119),
    ('Myszka dla graczy', 1, 0, 0, 'Specjalizowana mysz komputerowa zaprojektowana dla graczy.', 120),
    ('Projektor planetarny', 1, 0, 0, 'Urządzenie do wyświetlania obrazu planet i gwiazd na suficie.', 121),
    ('Wyciskarka do soków', 1, 0, 0, 'Urządzenie służące do wyciskania świeżych soków z owoców i warzyw.', 122),
    ('Konsola do gier stacjonarna', 1, 0, 0, 'Stacjonarna konsola do gier wideo podłączana do telewizora.', 123),
    ('Kamera sportowa 4K', 1, 0, 0, 'Kompaktowa kamera do nagrywania sportowych wydarzeń w jakości 4K.', 124),
    ('Rozproszone centrum danych', 1, 0, 0, 'Infrastruktura umożliwiająca przechowywanie i przetwarzanie danych w rozproszony sposób.', 125),
    ('Smartfon z podwójnym aparatem', 1, 0, 0, 'Telefon komórkowy wyposażony w dwie kamery do robienia zdjęć i nagrywania wideo.', 126),
    ('Słuchawki bezprzewodowe', 1, 0, 0, 'Bezprzewodowe słuchawki do odtwarzania muzyki i prowadzenia rozmów.', 127),
    ('Stacja dokująca', 1, 0, 0, 'Urządzenie służące do ładowania i synchronizacji danych z urządzeniami przenośnymi.', 128),
    ('Konsola do gier wirtualnej rzeczywistości', 1, 0, 0, 'Konsola umożliwiająca grę w wirtualnej rzeczywistości.', 129),
    ('Elektryczna deskorolka', 1, 0, 0, 'Przenośne urządzenie napędzane elektrycznie, służące do poruszania się po powierzchni.', 130),
    ('Klawiatura bezprzewodowa', 1, 0, 0, 'Bezprzewodowa klawiatura komputerowa.', 131),
    ('Kamera do monitoringu 4K', 1, 0, 0, 'Zaawansowane urządzenie do monitoringu w jakości 4K.', 132),
    ('Drukarka laserowa', 1, 0, 0, 'Urządzenie służące do drukowania dokumentów przy użyciu technologii laserowej.', 133),
    ('Przenośne głośniki Bluetooth', 1, 0, 0, 'Bezprzewodowe głośniki do odtwarzania muzyki z urządzeń mobilnych.', 134),
    ('Myszka optyczna', 1, 0, 0, 'Przenośna mysz komputerowa wykorzystująca technologię optyczną.', 135),
    ('Projektor multimedialny', 1, 0, 0, 'Urządzenie do wyświetlania obrazów i prezentacji multimedialnych.', 136),
    ('Smartfon z czytnikiem linii papilarnych', 1, 0, 0, 'Telefon komórkowy z wbudowanym czytnikiem linii papilarnych dla zwiększonego bezpieczeństwa.', 137),
    ('Głośniki studyjne', 1, 0, 0, 'Wysokiej jakości głośniki przeznaczone do monitorowania i edycji dźwięku.', 138),
    ('Tablet graficzny', 1, 0, 0, 'Urządzenie do ręcznego rysowania i tworzenia grafiki cyfrowej.', 139),
    ('Mikser kuchenny', 1, 0, 0, 'Urządzenie służące do mieszania, ubijania i rozdrabniania składników kuchennych.', 140),
    ('Konsola do gier retro', 1, 0, 0, 'Konsola przeznaczona do grania w klasyczne gry wideo.', 141),
    ('Projektor do gier', 1, 0, 0, 'Urządzenie do wyświetlania gier wideo na dużym ekranie.', 142),
    ('Smartwatch z funkcją GPS', 1, 0, 0, 'Zegarek z wbudowanym odbiornikiem GPS do monitorowania lokalizacji.', 143),
    ('Dron z kamerą', 1, 0, 0, 'Bezzałogowy statek powietrzny wyposażony w kamerę do nagrywania wideo.', 144),
    ('Stabilizator kamery', 1, 0, 0, 'Urządzenie służące do utrzymania stabilności kamery podczas nagrywania.', 44),
    ('Termometr elektroniczny', 1, 0, 0, 'Elektroniczny przyrząd do pomiaru temperatury.', 89),
    ('Drukarka laserowa kolorowa', 1, 0, 0, 'Profesjonalna drukarka laserowa umożliwiająca drukowanie kolorowych dokumentów.', 56),
    ('Skaner dokumentów', 1, 0, 0, 'Urządzenie służące do skanowania dokumentów i przekształcania ich w pliki cyfrowe.', 57),
    ('Maszyna do pisania', 1, 0, 0, 'Klasyczna maszyna do pisania mechaniczna.', 57),
    ('Kserokopiarka', 1, 0, 0, 'Urządzenie służące do tworzenia kopii dokumentów.', 78),
    ('Wielofunkcyjne urządzenie biurowe', 1, 0, 0, 'Urządzenie łączące funkcje drukarki, skanera i kserokopiarki.', 67),
    ('Biurko', 1, 0, 0, 'Meble biurowe służące do pracy i organizacji przestrzeni.', 55),
    ('Krzesło biurowe', 1, 0, 0, 'Wygodne krzesło zaprojektowane do pracy biurowej.', 43),
    ('Półki na dokumenty', 1, 0, 0, 'Meble do przechowywania i organizowania dokumentów.', 56),
    ('Kalkulator biurowy', 1, 0, 0, 'Urządzenie służące do wykonywania obliczeń matematycznych.', 54),
    ('Telefon biurowy', 1, 0, 0, 'Stacjonarny telefon przeznaczony do użytku w biurach.', 76),
    ('Papier do drukarki', 1, 0, 0, 'Specjalny papier przeznaczony do drukarek.', 98),
    ('Długopis', 1, 0, 0, 'Standardowe narzędzie do pisania z tuszem.', 99),
    ('Notes', 1, 0, 0, 'Przenośny zeszyt służący do zapisywania notatek.', 88),
    ('Bindowanie', 1, 0, 0, 'Urządzenie do łączenia kartek papieru w formie książki.', 77),
    ('Przenośna kalkulacja', 1, 0, 0, 'Kalkulator zasilany bateriami, który można nosić w kieszeni.', 66),
    ('Lampa biurowa', 1, 0, 0, 'Źródło światła przeznaczone do biurka, zapewniające odpowiednie oświetlenie.', 55),
    ('Kosz na śmieci', 1, 0, 0, 'Pojemnik służący do gromadzenia i utylizacji odpadków w biurze.', 44),
    ('Długopis żelowy', 1, 0, 0, 'Długopis z wkładem żelowym, zapewniający płynne i precyzyjne pisanie.', 33),
    ('Zestaw markerów', 1, 0, 0, 'Zestaw kolorowych markerów do pisania i zaznaczania.', 22),
    ('Regał na dokumenty', 1, 0, 0, 'Meble biurowe z półkami przeznaczone do przechowywania dokumentów.', 56),
    ('Tablica korkowa', 1, 0, 0, 'Powierzchnia korkowa służąca do przypinania notatek i informacji.', 75),
    ('Stojak na ulotki', 1, 0, 0, 'Układane stojaki przeznaczone do wyeksponowania ulotek i broszur.', 43),
    ('Zestaw do pisania', 1, 0, 0, 'Kompletny zestaw narzędzi do pisania, w tym długopisy, ołówki i gumki.', 5),
    ('Organizer biurowy', 1, 0, 0, 'Przyrząd służący do przechowywania i porządkowania materiałów biurowych.', 66),
    ('Kubek na długopisy', 1, 0, 0, 'Pojemnik na długopisy i inne artykuły piśmiennicze.', 6),
    ('Podstawka pod laptopa', 1, 0, 0, 'Podstawa pod laptopa, zapewniająca wygodniejszą pozycję podczas pracy.', 5),
    ('Zestaw do czyszczenia biurka', 1, 0, 0, 'Zestaw narzędzi i środków czyszczących do utrzymania czystości biurka.', 4),
    ('Przenośny dysk twardy', 1, 0, 0, 'Zewnętrzny dysk twardy służący do przechowywania i przenoszenia danych.', 3),
    ('Stapler', 1, 0, 0, 'Urządzenie do spinania kartek papieru zszywkami.', 2),
    ('Kalendarz biurowy', 1, 0, 0, 'Kalendarz służący do planowania i organizowania zadań w biurze.', 1),
    ('Drukarka laserowa czarno-biała', 1, 0, 0, 'Profesjonalna drukarka laserowa umożliwiająca drukowanie czarno-białych dokumentów.', 89),
    ('Rozdzielacz HDMI', 1, 0, 0, 'Urządzenie służące do podziału sygnału HDMI na wiele wyjść.', 132),
    ('Gilotyna do papieru', 1, 0, 0, 'Urządzenie do precyzyjnego cięcia papieru.', 71),
    ('Tablica magnetyczna', 1, 0, 0, 'Powierzchnia magnetyczna służąca do pisania i wywieszania notatek.', 102),
    ('Podstawka pod monitor', 1, 0, 0, 'Podstawa pod monitor, zapewniająca wygodniejszą pozycję podczas pracy.', 56),
    ('Oczyszczacz powietrza', 1, 0, 0, 'Urządzenie służące do usuwania zanieczyszczeń z powietrza w biurze.', 126),
    ('Etui na dokumenty', 1, 0, 0, 'Pojemnik służący do przechowywania i organizowania dokumentów.', 98),
    ('Stojak na kubki', 1, 0, 0, 'Układany stojak przeznaczony do przechowywania kubków i filiżanek.', 67),
    ('Gilotyna do plastiku', 1, 0, 0, 'Urządzenie do precyzyjnego cięcia plastiku.', 54),
    ('Monitor 27 cali', 1, 0, 0, 'Duży monitor o przekątnej 27 cali do wyświetlania treści multimedialnych.', 73),
    ('Pudełko na dokumenty', 1, 0, 0, 'Pojemnik służący do przechowywania i organizowania dokumentów.', 94),
    ('Dziurkacz', 1, 0, 0, 'Urządzenie służące do wykonywania otworów w kartkach papieru.', 61),
    ('Przenośna drukarka', 1, 0, 0, 'Mała, przenośna drukarka do drukowania dokumentów w podróży.', 112),
    ('Papier do ksero', 1, 0, 0, 'Specjalny papier przeznaczony do kopiowania dokumentów.', 86),
    ('Bindownica', 1, 0, 0, 'Urządzenie służące do łączenia kartek papieru w formie książki.', 65),
    ('Stojak na katalogi', 1, 0, 0, 'Układany stojak przeznaczony do przechowywania katalogów i broszur.', 76),
    ('Klawiatura bezprzewodowa', 1, 0, 0, 'Bezprzewodowa klawiatura do wprowadzania tekstu na komputerze.', 143),
    ('Uchwyt na słuchawki', 1, 0, 0, 'Uchwyt służący do przechowywania słuchawek na biurku.', 50),
    ('Podstawka na dokumenty', 1, 0, 0, 'Podkładka służąca do przechowywania i organizowania dokumentów na biurku.', 82),
    ('Lupa', 1, 0, 0, 'Urządzenie powiększające służące do czytania i oglądania drobnych szczegółów.', 107),
    ('Zestaw do czyszczenia ekranu', 1, 0, 0, 'Zestaw narzędzi i środków czyszczących do czyszczenia ekranów urządzeń elektronicznych.', 91),
    ('Stojak na kubek na długopisy', 1, 0, 0, 'Układany stojak służący do przechowywania kubka na długopisy i inne artykuły piśmiennicze.', 78),
    ('Podkładka na biurko', 1, 0, 0, 'Podkładka służąca do ochrony powierzchni biurka i zapewnienia wygodnego miejsca do pisania.', 64),
    ('Otwieracz do listów', 1, 0, 0, 'Narzędzie służące do otwierania kopert i listów.', 110),
    ('Klawiatura mechaniczna', 1, 0, 0, 'Klawiatura wyposażona w mechaniczne przełączniki, zapewniająca precyzyjne i wygodne pisanie.', 134),
    ('Stojak na tablety', 1, 0, 0, 'Układany stojak przeznaczony do przechowywania i wygodnego korzystania z tabletów.', 96),
    ('Kamera internetowa', 1, 0, 0, 'Kamera służąca do prowadzenia wideokonferencji i komunikacji przez internet.', 120),
    ('Stojak na książki', 1, 0, 0, 'Układany stojak przeznaczony do przechowywania książek i podręczników.', 80),
    ('Zegar na biurko', 1, 0, 0, 'Zegar służący do wyświetlania aktualnego czasu na biurku.', 102),
    ('Niszczarka dokumentów', 1, 0, 0, 'Urządzenie służące do niszczenia poufnych dokumentów poprzez ich rozdrobnienie.', 96),
    ('Stojak na segregatory', 1, 0, 0, 'Układany stojak przeznaczony do przechowywania segregatorów i teczek.', 64),
    ('Skaner dokumentów', 1, 0, 0, 'Urządzenie służące do skanowania i cyfryzowania dokumentów.', 112),
    ('Przycisk przełącznika', 1, 0, 0, 'Przycisk służący do włączania i wyłączania urządzeń elektronicznych.', 76),
    ('Stojak na kable', 1, 0, 0, 'Układany stojak przeznaczony do porządkowania i prowadzenia kabli w biurze.', 80),
    ('Podgrzewacz do kawy', 1, 0, 0, 'Urządzenie służące do podgrzewania i utrzymywania ciepłej kawy.', 98),
    ('Wskaźnik laserowy', 1, 0, 0, 'Urządzenie emitujące cienki promień światła laserowego służące do wskazywania na ekranach.', 120),
    ('Podstawka pod telefon', 1, 0, 0, 'Podstawa służąca do stabilnego ustawienia telefonu na biurku.', 86),
    ('Podkładka na rękę', 1, 0, 0, 'Podkładka służąca do wsparcia nadgarstka podczas pisania na klawiaturze.', 143),
    ('Zestaw do czyszczenia drukarki', 1, 0, 0, 'Zestaw narzędzi i środków czyszczących do utrzymania drukarki w czystości.', 73),
    ('Podnośnik monitora', 1, 0, 0, 'Podstawa umożliwiająca podniesienie monitora na wyższą pozycję.', 98),
    ('Książka adresowa', 1, 0, 0, 'Książka służąca do przechowywania danych kontaktowych.', 61),
    ('Etui na kable', 1, 0, 0, 'Pojemnik służący do przechowywania i organizowania kabli i przewodów.', 117),
    ('Podstawka na klawiaturę i mysz', 1, 0, 0, 'Podstawa służąca do wygodnego ustawienia klawiatury i myszy na biurku.', 82),
    ('Papier do drukarki', 1, 0, 0, 'Specjalny papier przeznaczony do drukowania dokumentów na drukarkach.', 76),
    ('Podstawka pod monitor regulowana', 1, 0, 0, 'Regulowana podstawa pod monitor, umożliwiająca dostosowanie wysokości i kąta widzenia.', 89),
    ('Podkładka na mysz', 1, 0, 0, 'Podkładka służąca do wygodnego poruszania myszą na biurku.', 102),
    ('Papier kolorowy', 1, 0, 0, 'Kolorowy papier przeznaczony do drukowania kreatywnych projektów.', 112),
    ('Wieszak na płaszcze', 1, 0, 0, 'Wieszak służący do zawieszania płaszczy i kurtek.', 58),
    ('Organizer na biurko', 1, 0, 0, 'Pojemnik służący do przechowywania i organizowania artykułów biurowych na biurku.', 71),
    ('Podstawka na dokumenty z regulacją kąta', 1, 0, 0, 'Podstawa z możliwością regulacji kąta nachylenia, umożliwiająca wygodne czytanie dokumentów.', 126),
    ('Stojak na klawiaturę', 1, 0, 0, 'Układany stojak przeznaczony do przechowywania klawiatury podczas jej nieużywania.', 67),
    ('Wieszak na klucze', 1, 0, 0, 'Wieszak służący do przechowywania kluczy i innych drobnych przedmiotów.', 54),
    ('Podstawka na monitor z głośnikami', 1, 0, 0, 'Podstawa pod monitor wyposażona w wbudowane głośniki, umożliwiająca odtwarzanie dźwięku.', 73),
    ('Kalendarz biurkowy', 1, 0, 0, 'Kalendarz umieszczany na biurku, służący do zaznaczania terminów i planowania.', 98),
    ('Stojak na notesy', 1, 0, 0, 'Układany stojak przeznaczony do przechowywania notesów i zapisków.', 61),
    ('Pudełko na biżuterię', 1, 0, 0, 'Pojemnik służący do przechowywania biżuterii i drobnych akcesoriów.', 112),
    ('Stojak na dokumenty', 1, 0, 0, 'Układany stojak przeznaczony do przechowywania i organizowania dokumentów na biurku.', 76),
    ('Podstawka na telefon z ładowarką bezprzewodową', 1, 0, 0, 'Podstawa z wbudowaną ładowarką bezprzewodową, umożliwiająca ładowanie telefonu podczas ustawienia na biurku.', 120),
    ('Stojak na dokumenty ściankowy', 1, 0, 0, 'Stojak montowany na ścianie służący do przechowywania i organizowania dokumentów.', 78),
    ('Kalkulator biurowy', 1, 0, 0, 'Kalkulator przeznaczony do wykonywania podstawowych operacji matematycznych.', 102),
    ('Tablica korkowa', 1, 0, 0, 'Tablica pokryta korkiem służąca do przypinania notatek, zdjęć i innych materiałów.', 143),
    ('Wieszak na torby', 1, 0, 0, 'Wieszak służący do zawieszania torby lub plecaka na biurku.', 73),
    ('Stojak na płyty CD/DVD', 1, 0, 0, 'Układany stojak przeznaczony do przechowywania płyt CD i DVD.', 80),
    ('Podstawka pod laptopa z wentylatorem', 1, 0, 0, 'Podstawa pod laptopa wyposażona w wbudowany wentylator, zapewniająca lepsze chłodzenie urządzenia.', 91),
    ('Zestaw narzędzi biurowych', 1, 0, 0, 'Zestaw narzędzi służących do wykonywania różnych czynności biurowych, takich jak przycinanie, zszywanie itp.', 107),
    ('Podstawka na dokumenty z lampką', 1, 0, 0, 'Podstawa z wbudowaną lampką, służąca do czytania dokumentów w warunkach słabego oświetlenia.', 50),
    ('Podkładka pod ręce z podgrzewaczem', 1, 0, 0, 'Podkładka służąca do podparcia nadgarstków podczas pracy przy komputerze, wyposażona w funkcję podgrzewania.', 82),
    ('Wieszak na przewody', 1, 0, 0, 'Wieszak służący do porządkowania i prowadzenia przewodów na biurku.', 96),
    ('Zestaw do czyszczenia klawiatury', 1, 0, 0, 'Zestaw narzędzi i środków czyszczących do utrzymania klawiatury w czystości.', 120)