INSERT INTO [dbo].[Department] ([Name], [FacultyID])
VALUES
    ('Katedra Cybernetyki i Systemów Informatycznych', 24),
    ('Katedra Mechatroniki i Robotyki', 26),
    ('Katedra Architektury Krajobrazu', 22),
    ('Katedra Konstrukcji Budowlanych', 23),
    ('Katedra Energetyki Odnawialnej', 25),
    ('Katedra Górnictwa i Geoinżynierii', 30),
    ('Katedra Informatyki Stosowanej', 27),
    ('Katedra Inżynierii Materiałowej i Metalurgii', 28),
    ('Katedra Matematyki Finansowej', 31),
    ('Katedra Technologii Maszyn i Urządzeń', 29),
    ('Katedra Zarządzania Projektami', 34),
    ('Katedra Inteligentnych Systemów Transportowych', 32),
    ('Katedra Architektury Systemów Komputerowych', 24),
    ('Katedra Technologii Energii Jądrowej', 25),
    ('Katedra Inżynierii Środowiska', 23),
    ('Katedra Inżynierii Morskiej', 33),
    ('Katedra Systemów Komunikacyjnych', 26),
    ('Katedra Fizyki Technicznej', 27),
    ('Katedra Automatyki i Robotyki Przemysłowej', 29),
    ('Katedra Teleinformatyki', 24),
    ('Katedra Elektroenergetyki i Transportu Elektrycznego', 26),
    ('Katedra Inżynierii Bezpieczeństwa', 23),
    ('Katedra Inżynierii Biomedycznej', 28),
    ('Katedra Zarządzania Produkcją', 34),
    ('Katedra Inżynierii Chemicznej', 25),
    ('Katedra Geodezji i Kartografii', 30),
    ('Katedra Systemów Inżynierii Wiedzy', 27),
    ('Katedra Inżynierii Ruchu Drogowego', 32),
    ('Katedra Inżynierii Elektronicznej', 24),
    ('Katedra Inżynierii Kształtowania Środowiska', 23),
    ('Katedra Bioinżynierii', 28),
    ('Katedra Marketingu Technicznego', 34),
    ('Katedra Inżynierii Materiałowej', 28),
    ('Katedra Energetyki Cieplnej i Aparatów', 25),
    ('Katedra Geoinformacji i Teledetekcji', 30),
    ('Katedra Systemów Multimedialnych', 27),
    ('Katedra Logistyki Technicznej', 34),
    ('Katedra Biotechnologii i Bioinformatyki', 28),
    ('Katedra Systemów Wytwarzania', 29),
    ('Katedra Inżynierii Chłodnictwa i Klimatyzacji', 25),
    ('Katedra Gospodarki Przestrzennej', 34),
    ('Katedra Inżynierii Geologicznej', 30),
    ('Katedra Ochrony Środowiska i Gospodarki Odpadami', 23),
    ('Katedra Systemów Kontroli i Diagnostyki', 26),
    ('Katedra Inżynierii Materiałowej i Ceramiki', 28),
    ('Katedra Informatyki Medycznej', 27),
    ('Katedra Logistyki Wewnętrznej', 34),
    ('Katedra Inżynierii Wodnej i Sanitarnej', 23),
    ('Katedra Geotechniki i Geomechaniki', 30),
    ('Katedra Inżynierii Wieloskalowej', 29),
    ('Katedra Inżynierii Jakości i Ergonomii', 34),
    ('Katedra Inżynierii Produkcji', 29),
    ('Katedra Inżynierii Wymiarowania i Kontroli', 24),
    ('Katedra Biologii Technicznej', 28),
    ('Katedra Inżynierii Ruchu i Transportu', 32),
    ('Katedra Inżynierii Zarządzania', 34),
    ('Katedra Inżynierii Termicznej', 25),
    ('Katedra Inżynierii Morskiej i Offshore', 33),
    ('Katedra Inżynierii Komputerowej', 24),
    ('Katedra Inżynierii Jądrowej i Reaktorowej', 25),
    ('Katedra Inżynierii Lądowej', 23),
    ('Katedra Inżynierii Chemicznej i Procesowej', 28),
    ('Katedra Inżynierii Systemów', 26),
    ('Katedra Inżynierii Telekomunikacyjnej', 27),
    ('Katedra Inżynierii Materiałowej i Kompozytów', 28),
    ('Katedra Inżynierii Środowiska i Infrastruktury', 23),
    ('Katedra Inżynierii Przemysłowej', 29),
    ('Katedra Inżynierii Wytwarzania i Montażu', 24),
    ('Katedra Inżynierii Biomateriałów', 28),
    ('Katedra Inżynierii Komunikacyjnej', 32),
    ('Katedra Inżynierii Produkcji i Logistyki', 34),
    ('Katedra Inżynierii Informatycznej', 24),
    ('Katedra Inżynierii Energetyki Jądrowej', 25),
    ('Katedra Inżynierii Środowiska i Budownictwa', 23),
    ('Katedra Inżynierii Chemicznej i Technologii Środowiska', 28),
    ('Katedra Inżynierii Systemów Informatycznych', 26),
    ('Katedra Inżynierii Telekomunikacyjnej i Multimedialnej', 27),
    ('Katedra Inżynierii Materiałowej i Wytrzymałości Materiałów', 28),
    ('Katedra Inżynierii Bioinżynierskiej', 28),
    ('Katedra Inżynierii Transportu', 32),
    ('Katedra Inżynierii Produkcji i Systemów Zarządzania', 34),
    ('Katedra Inżynierii Energii Cieplnej', 25),
    ('Katedra Inżynierii Morskiej i Żeglugi', 33),
    ('Katedra Inżynierii Komputerowej i Sztucznej Inteligencji', 24),
    ('Katedra Inżynierii Jądrowej i Fizyki Jądrowej', 25),
    ('Katedra Inżynierii Środowiska i Infrastruktury Miejskiej', 23),
    ('Katedra Inżynierii Chemicznej i Procesowej', 28),
    ('Katedra Inżynierii Systemów Elektronicznych', 26),
    ('Katedra Inżynierii Teleinformatycznej', 27),
    ('Katedra Inżynierii Materiałowej i Metaloznawstwa', 28),
    ('Katedra Inżynierii Biomedycznej', 28),
    ('Katedra Inżynierii Ruchu Drogowego i Transportu', 32),
    ('Katedra Inżynierii Produkcji i Zarządzania', 34),
    ('Katedra Inżynierii Termicznej i Przemysłowej', 25),
    ('Katedra Inżynierii Morskiej i Offshore', 33),
    ('Katedra Inżynierii Komputerowej i Sieci', 24),
    ('Katedra Inżynierii Jądrowej i Reaktorowej', 25),
    ('Katedra Inżynierii Lądowej i Budownictwa', 23),
    ('Katedra Inżynierii Chemicznej i Technologii Procesów', 28),
    ('Katedra Inżynierii Systemów Komunikacyjnych', 26)